DROP TABLE IF EXISTS MENU;
CREATE TABLE MENU(
ID VARCHAR(20) NOT NULL PRIMARY KEY,
NAME VARCHAR(100) NOT NULL,
PARENT_ID VARCHAR(20),
LEVEL INTEGER NOT NULL,
SEQUENCE INTEGER NOT NULL,
LEAF VARCHAR(1),
FUNCTION_CODE VARCHAR(50),
REMARK VARCHAR(500),
CREATE_TIME TIMESTAMP
);

DROP TABLE IF EXISTS USER_SETTING;
CREATE TABLE USER_SETTING(
ID VARCHAR(20) NOT NULL PRIMARY KEY,
USER_ID VARCHAR(50) NOT NULL,
HOME_FUNCTION_CODE VARCHAR(50)
);

DROP TABLE IF EXISTS USER_FAV_FUNCTION;
CREATE TABLE USER_FAV_FUNCTION(
ID VARCHAR(20) NOT NULL PRIMARY KEY,
SETTING_ID VARCHAR(20) NOT NULL,
FUNCTION_CODE VARCHAR(50) NOT NULL
);
