DROP TABLE IF EXISTS USER_SETTING;

CREATE TABLE USER_SETTING(
ID VARCHAR(50) NOT NULL PRIMARY KEY,
USER_ID VARCHAR(50) NOT NULL,
HOME_FUNCTION_CODE VARCHAR(50)
);
    
DROP TABLE IF EXISTS USER_FAV_FUNCTION;

CREATE TABLE USER_FAV_FUNCTION(
ID VARCHAR(50) NOT NULL PRIMARY KEY,
USER_SETTING_ID VARCHAR(50) NOT NULL,
FUNCTION_CODE VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS USER_SETTING_FAV_FUNCTIONS;

CREATE TABLE USER_SETTING_FAV_FUNCTIONS(
 USER_SETTING_ID VARCHAR(50),
 FAV_FUNCTIONS_ID VARCHAR(50)
);
